module.exports = {
  projects: [
    '<rootDir>/libs/api/providers/config',
    '<rootDir>/libs/api/providers/router',
    '<rootDir>/libs/api/providers/logger',
    '<rootDir>/libs/tools/eslint-config-codelab',
    '<rootDir>/libs/tools/plugins/codelab',
    '<rootDir>/libs/shared/common',
    // '<rootDir>/libs/shared/interface/node',
    // '<rootDir>/libs/shared/interface/graph',
    // '<rootDir>/libs/shared/interface/props',
    // '<rootDir>/libs/shared/interface/model',
    // '<rootDir>/libs/shared/interface/tree',
    // '<rootDir>/libs/shared/interface/component',
    '<rootDir>/libs/core/graph',
    '<rootDir>/libs/core/model',
    '<rootDir>/libs/core/props',
    '<rootDir>/libs/core/node',
    '<rootDir>/libs/core/traversal',
    '<rootDir>/libs/core/tree',
    '<rootDir>/libs/shared/utils',
    '<rootDir>/libs/shared/event',
    '<rootDir>/apps/web',
    '<rootDir>/libs/core/renderer',
    '<rootDir>/libs/state/app',
    '<rootDir>/libs/state/node',
    '<rootDir>/libs/state/modal',
    '<rootDir>/libs/ui/antd',
    '<rootDir>/libs/ui/d3',
    '<rootDir>/libs/ui/component',
    '<rootDir>/libs/ui/hoc',
    '<rootDir>/libs/state/apollo',
    '<rootDir>/apps/api/external',
    '<rootDir>/apps/api/graph',
    '<rootDir>/libs/state/vertex',
    '<rootDir>/libs/shared/interface/graph-v2',
    '<rootDir>/libs/shared/interface/machine',
    '<rootDir>/libs/shared/factory',
    '<rootDir>/libs/shared/interface/mapper',
    '<rootDir>/libs/shared/interface/collections',
    '<rootDir>/libs/ddd/backend',
    '<rootDir>/libs/ddd/frontend',
    '<rootDir>/libs/ddd/modules/users',
    '<rootDir>/apps/api/codelab',
    '<rootDir>/libs/ddd/modules/users-stories',
    '<rootDir>/libs/ddd/modules/layout-stories',
  ],
}
