import {
  FormUniforms,
  FormUniformsProps,
} from '@codelab/frontend/view/components'
import React from 'react'
import { TypeTree } from '../typeTree'
import { interfaceToJsonSchema } from './transformations'

export interface InterfaceFormProps<TData>
  extends Omit<FormUniformsProps<TData>, 'schema'> {
  interfaceTree: TypeTree
}

/**
 * Uniforms form generated by an Interface
 */
export const InterfaceForm = <TData extends any>({
  interfaceTree,
  children,
  ...props
}: React.PropsWithChildren<InterfaceFormProps<TData>>) => {
  return (
    <FormUniforms schema={interfaceToJsonSchema(interfaceTree)} {...props}>
      {children}
    </FormUniforms>
  )
}

InterfaceForm.displayName = 'InterfaceForm'
InterfaceForm.whyDidYouRender = true
