export enum StateNameEntity {
  IDLE = 'IDLE',
  LOADING = 'LOADING',
  LOADED = 'LOADED',
  EDITING = 'EDITING',
  EDIT_SUBMITTING = 'EDIT_SUBMITING',
  EDITED = 'EDITED',
  CREATING = 'CREATING',
  CREATED = 'CREATED',
  DELETED = 'DELETED',
  DELETING = 'DELETING',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
}
