import { IAtomType } from '@codelab/shared/abstract/core'

/**
 * Maps the name of the csv files to their atom type
 */
export const csvNameToAtomTypeMap: Record<string, IAtomType> = {
  //
  // Antd:
  //
  Affix: IAtomType.AntDesignAffix,
  // 'Alert--Alert.ErrorBoundary': IAtomType.AntDesignAlert,
  'Anchor--Anchor Props': IAtomType.AntDesignAnchor,
  'Anchor--Link Props': IAtomType.AntDesignAnchorLink,
  Avatar: IAtomType.AntDesignAvatar,
  // 'Avatar--Avatar.Group (4.5.0+)': IAtomType.AntDesignAvatar,
  BackTop: IAtomType.AntDesignBackTop,
  Badge: IAtomType.AntDesignBadge,
  // 'Badge--Badge.Ribbon (4.5.0+)': IAtomType.AntDesignBadge,
  Breadcrumb: IAtomType.AntDesignBreadcrumb,
  'Breadcrumb--Breadcrumb.Item': IAtomType.AntDesignBreadcrumbItem,
  // 'Breadcrumb--Breadcrumb.Separator': IAtomType.AntDesignBreadcrumb,
  Button: IAtomType.AntDesignButton,
  Calendar: IAtomType.AntDesignCalendar,
  Card: IAtomType.AntDesignCard,
  'Card--Card.Grid': IAtomType.AntDesignCardGrid,
  'Card--Card.Meta': IAtomType.AntDesignCardMeta,
  // 'Cascader--showSearch': IAtomType.AntDesignCascader,
  'Checkbox--Props': IAtomType.AntDesignCheckbox,
  Collapse: IAtomType.AntDesignCollapse,
  'Collapse--Collapse.Panel': IAtomType.AntDesignCollapsePanel,
  Comment: IAtomType.AntDesignComment,
  ConfigProvider: IAtomType.AntDesignConfigProvider,
  DatePicker: IAtomType.AntDesignDatePicker,
  'DatePicker--Common API': IAtomType.AntDesignDatePicker,
  'DatePicker--DatePicker[picker=month]': IAtomType.AntDesignDatePicker,
  'DatePicker--DatePicker[picker=quarter]': IAtomType.AntDesignDatePicker,
  'DatePicker--DatePicker[picker=week]': IAtomType.AntDesignDatePicker,
  'DatePicker--DatePicker[picker=year]': IAtomType.AntDesignDatePicker,
  // 'DatePicker--RangePicker': IAtomType.AntDesignDatePicker,
  Descriptions: IAtomType.AntDesignDescriptions,
  'Descriptions--DescriptionItem': IAtomType.AntDesignDescriptionsItem,
  Divider: IAtomType.AntDesignDivider,
  Drawer: IAtomType.AntDesignDrawer,
  Dropdown: IAtomType.AntDesignDropdown,
  // 'Dropdown--Dropdown.Button': IAtomType.AntDesignDropdown,
  Empty: IAtomType.AntDesignEmpty,
  Form: IAtomType.AntDesignForm,
  // 'Form--FormInstance': IAtomType.AntDesignForm,
  'Grid--Col': IAtomType.AntDesignGridCol,
  'Grid--Row': IAtomType.AntDesignGridRow,
  'Icon--Common Icon': IAtomType.AntDesignIcon,
  // 'Icon--Custom Icon': IAtomType.AntDesignIcon,
  // Image: IAtomType.AntDesignImage,
  Input: IAtomType.AntDesignInput,
  // 'Input--Input.TextArea': IAtomType.AntDesignInput,
  Layout: IAtomType.AntDesignLayout,
  'Layout--Layout.Sider': IAtomType.AntDesignLayoutSider,
  List: IAtomType.AntDesignList,
  'List--List.Item': IAtomType.AntDesignListItem,
  'List--List.Item.Meta': IAtomType.AntDesignListItemMeta,
  // 'List--List grid props': IAtomType.AntDesignList,
  // 'List--pagination': IAtomType.AntDesignList,
  'Mentions--Mention': IAtomType.AntDesignMentions,
  'Mentions--Option': IAtomType.AntDesignMentionsOption,
  Menu: IAtomType.AntDesignMenu,
  'Menu--Menu.Item': IAtomType.AntDesignMenuItem,
  'Menu--Menu.ItemGroup': IAtomType.AntDesignMenuItemGroup,
  'Menu--Menu.SubMenu': IAtomType.AntDesignMenuSubMenu,
  PageHeader: IAtomType.AntDesignPageHeader,
  Pagination: IAtomType.AntDesignPagination,
  Popconfirm: IAtomType.AntDesignPopconfirm,
  Popover: IAtomType.AntDesignPopover,
  'Progress--type=circle': IAtomType.AntDesignProgress,
  'Progress--type=dashboard': IAtomType.AntDesignProgress,
  'Progress--type=line': IAtomType.AntDesignProgress,
  'Radio--Radio_Radio.Button': IAtomType.AntDesignRadio,
  'Radio--RadioGroup': IAtomType.AntDesignRadioGroup,
  Result: IAtomType.AntDesignResult,
  // 'Select--OptGroup props': IAtomType.AntDesignSelect,
  'Select--Option props': IAtomType.AntDesignSelectOption,
  'Select--Select props': IAtomType.AntDesignSelect,
  Skeleton: IAtomType.AntDesignSkeleton,
  'Skeleton--SkeletonAvatarProps': IAtomType.AntDesignSkeleton,
  'Skeleton--SkeletonButtonProps': IAtomType.AntDesignSkeleton,
  'Skeleton--SkeletonInputProps': IAtomType.AntDesignSkeleton,
  'Skeleton--SkeletonParagraphProps': IAtomType.AntDesignSkeleton,
  'Skeleton--SkeletonTitleProps': IAtomType.AntDesignSkeleton,
  'Slider--range': IAtomType.AntDesignSlider,
  Space: IAtomType.AntDesignSpace,
  Spin: IAtomType.AntDesignSpin,
  Steps: IAtomType.AntDesignSteps,
  'Steps--Steps.Step': IAtomType.AntDesignStepsStep,
  Table: IAtomType.AntDesignTable,
  // 'Table--Column': IAtomType.AntDesignTable,
  // 'Table--ColumnGroup': IAtomType.AntDesignTable,
  // 'Table--expandable': IAtomType.AntDesignTable,
  // 'Table--pagination': IAtomType.AntDesignTable,
  // 'Table--rowSelection': IAtomType.AntDesignTable,
  // 'Table--scroll': IAtomType.AntDesignTable,
  // 'Table--selection': IAtomType.AntDesignTable,
  Tabs: IAtomType.AntDesignTabs,
  'Tabs--Tabs.TabPane': IAtomType.AntDesignTabsTabPane,
  Tag: IAtomType.AntDesignTag,
  // 'Tag--Tag.CheckableTag': IAtomType.AntDesignTag,
  Timeline: IAtomType.AntDesignTimeline,
  'Timeline--Timeline.Item': IAtomType.AntDesignTimelineItem,
  // 'TimePicker--RangePicker': IAtomType.AntDesignTimePicker,
  'Tooltip--Common API': IAtomType.AntDesignTooltip,
  // 'Transfer--Render Props': IAtomType.AntDesignTransfer,
  // 'Tree--DirectoryTree props': IAtomType.AntDesignTree,
  'Tree--Tree props': IAtomType.AntDesignTree,
  'Tree--TreeNode props': IAtomType.AntDesignTreeNode,
  'TreeSelect--Tree props': IAtomType.AntDesignTreeSelect,
  'TreeSelect--TreeNode props': IAtomType.AntDesignTreeSelect,
  // 'Typography--copyable': IAtomType.AntDesignTypography,
  // 'Typography--editable': IAtomType.AntDesignTypography,
  // 'Typography--ellipsis': IAtomType.AntDesignTypography,
  'Typography--Typography.Paragraph': IAtomType.AntDesignTypographyParagraph,
  'Typography--Typography.Text': IAtomType.AntDesignTypographyText,
  'Typography--Typography.Title': IAtomType.AntDesignTypographyTitle,
  'Upload--UploadFile': IAtomType.AntDesignUpload,
  Image: IAtomType.AntDesignImage,
  Modal: IAtomType.AntDesignModal,
  'Form--Item': IAtomType.AntDesignFormItem,

  //
  // Custom components:
  //
  Query: IAtomType.Query,
  TextList: IAtomType.TextList,
  Text: IAtomType.Text,
  State: IAtomType.State,
}
