import { Theme as AntDTheme } from '@rjsf/antd'
import { withTheme } from '@rjsf/core'
import { Button } from 'antd'
import React, { ReactElement, useState } from 'react'
import { setSubmitControllerRef } from './Form-jsonSchema--ref'
import { JsonSchemaFormProps } from './Form-jsonSchema--types'
import { callCallbackOrArrayOfCallbacks } from 'libs/frontend/src/utils'

const ThemedForm = withTheme(AntDTheme)

/**
 * A form that's generated by a JSON schema.
 * Note: the form doesn't keep any state. If you don't pass formData and onChange and manage the state in another place, it will reset the values on every render
 */
export const JsonSchemaForm = <TData extends object>({
  submitRef,
  hideSubmitButton,
  onSubmitSuccess,
  onSubmitError,
  schema,
  onSubmit = () => null,
  initialFormData,
  submitButtonProps = {},
  rjsfFormProps = {},
}: JsonSchemaFormProps<TData>): ReactElement => {
  const [localFormData, setLocalFormData] = useState<TData>(initialFormData)

  return (
    <ThemedForm
      schema={schema}
      onSubmit={(err) =>
        onSubmit({ data: err.formData })
          .then((r: any) => {
            callCallbackOrArrayOfCallbacks(onSubmitSuccess, r)

            setLocalFormData({ ...initialFormData })
          })
          .catch((e: any) => {
            callCallbackOrArrayOfCallbacks(onSubmitError, e)
          })
      }
      onChange={(e) => setLocalFormData(e.formData)}
      formData={localFormData}
      {...rjsfFormProps}
    >
      {/* This button exists because by default the Form from rjsf includes a submit button and you can't configure it, only replace it by a custom one.
       Since we might not want to use it and we want to submit  using the submitController, we need a way to hide it.
       So we need to add our own button and hide it with display: none, it works
       */}
      <Button
        htmlType="submit"
        style={{
          ...submitButtonProps?.style,
          ...(hideSubmitButton ? { display: 'none' } : {}),
        }}
        // Expose only a submit controller ref, so that we don't have to expose the whole button ref
        ref={setSubmitControllerRef(submitRef)}
        {...submitButtonProps}
      >
        Submit
      </Button>
    </ThemedForm>
  )
}

export default JsonSchemaForm
