import { z } from 'zod'

export enum AtomTypeEnum {
  // Ant Design
  AntDesignAffix,
  AntDesignAlert,
  AntDesignAnchor,
  AntDesignAnchorLink,
  AntDesignAutoComplete,
  AntDesignAvatar,
  AntDesignBackTop,
  AntDesignBadge,
  AntDesignBreadcrumb,
  AntDesignBreadcrumbItem,
  AntDesignButton,
  AntDesignCalendar,
  AntDesignCard,
  AntDesignCardGrid,
  AntDesignCardMeta,
  AntDesignCarousel,
  AntDesignCascader,
  AntDesignCheckbox,
  AntDesignCollapse,
  AntDesignCollapsePanel,
  AntDesignComment,
  AntDesignConfigProvider,
  AntDesignDatePicker,
  AntDesignDescriptions,
  AntDesignDescriptionsItem,
  AntDesignDivider,
  AntDesignDrawer,
  AntDesignDropdown,
  AntDesignEmpty,
  AntDesignForm,
  AntDesignFormItem,
  AntDesignFormItemHook,
  AntDesignFormList,
  AntDesignGridCol,
  AntDesignGridRow,
  AntDesignIcon,
  AntDesignInput,
  AntDesignInputNumber,
  AntDesignLayout,
  AntDesignLayoutContent,
  AntDesignLayoutFooter,
  AntDesignLayoutHeader,
  AntDesignLayoutSider,
  AntDesignList,
  AntDesignListItem,
  AntDesignListItemMeta,
  AntDesignMapper,
  AntDesignMentions,
  AntDesignMentionsOption,
  AntDesignMenu,
  AntDesignMenuItem,
  AntDesignMenuItemGroup,
  AntDesignMenuSubMenu,
  AntDesignModal,
  AntDesignPageHeader,
  AntDesignPageContainer,
  AntDesignPagination,
  AntDesignPopconfirm,
  AntDesignPopover,
  AntDesignProgress,
  AntDesignProvider,
  AntDesignRglContainer,
  AntDesignRglItem,
  AntDesignRglResponsiveContainer,
  AntDesignRadio,
  AntDesignRadioGroup,
  AntDesignRate,
  AntDesignRenderComponent,
  AntDesignRenderContainer,
  AntDesignResult,
  AntDesignSelect,
  AntDesignSelectOption,
  AntDesignSkeleton,
  AntDesignSlider,
  AntDesignSpace,
  AntDesignSpin,
  AntDesignStatistic,
  AntDesignSteps,
  AntDesignStepsStep,
  AntDesignSwitch,
  AntDesignTable,
  AntDesignTabs,
  AntDesignTabsTabPane,
  AntDesignTag,
  AntDesignTimePicker,
  AntDesignTimeline,
  AntDesignTimelineItem,
  AntDesignTooltip,
  AntDesignTransfer,
  AntDesignTree,
  AntDesignTreeNode,
  AntDesignTreeSelect,
  AntDesignTypography,
  AntDesignTypographyParagraph,
  AntDesignTypographyText,
  AntDesignTypographyTitle,
  AntDesignUpload,

  // React
  ReactFragment,

  // Html
  HtmlA,
  HtmlDiv,
  HtmlP,
  HtmlSpan,
  HtmlText,
}

export const AtomType = z.nativeEnum(AtomTypeEnum)

export type AtomType = z.infer<typeof AtomType>
