import { Icon } from '@ant-design/compatible'
import {
  Affix,
  Alert,
  Anchor,
  AutoComplete,
  Avatar,
  BackTop,
  Badge,
  Breadcrumb,
  Button,
  Calendar,
  Card,
  Carousel,
  Cascader,
  Checkbox,
  Collapse,
  Comment,
  ConfigProvider,
  DatePicker,
  Descriptions,
  Divider,
  Drawer,
  Dropdown,
  Empty,
  Form,
  Input,
  InputNumber,
  Layout,
  List,
  Mentions,
  Menu,
  Modal,
  PageHeader,
  Pagination,
  Popconfirm,
  Popover,
  Progress,
  Radio,
  Rate,
  Result,
  Select,
  Skeleton,
  Slider,
  Space,
  Spin,
  Statistic,
  Steps,
  Switch,
  Tabs,
  Tag,
  TimePicker,
  Timeline,
  Tooltip,
  Transfer,
  Tree,
  TreeSelect,
  Typography,
  Upload,
} from 'antd'
import React from 'react'
import { AtomType } from '../interfaces'
// import {
//   CodelabForm,
//   CodelabHtml,
//   CodelabMapper,
//   CodelabTable,
//   Grid,
//   Provider,
//   RGL,
//   RenderComponent,
// } from '@codelab/alpha/ui/antd'

const PageContainer = ({ children, ...props }: any) => {
  return children ? <>{children}</> : <></>
}

/**
 * A map of VertexTypes to their corresponding React components.
 * When adding a new vertex type, add the corresponding mapping here
 */
export const elementTypeMap: Record<
  AtomType,
  React.ComponentType<any> | string
> = {
  [AtomType.ReactFragment]: React.Fragment,
  [AtomType.ReactHtmlDiv]: 'div',
  [AtomType.ReactHtmlP]: 'p',
  [AtomType.ReactHtmlA]: 'a',
  [AtomType.ReactHtmlSpan]: 'span',
  [AtomType.ReactText]: '',
  // [AtomType.ReactText]: CodelabHtml.Text,
  [AtomType.ReactIcon]: Icon,
  [AtomType.ReactMenu]: Menu,
  [AtomType.ReactMenuItem]: Menu.Item,
  [AtomType.ReactMenuItemGroup]: Menu.ItemGroup,
  [AtomType.ReactMenuSubMenu]: Menu.SubMenu,
  // [AtomType.ReactGridCol]: Grid.Col,
  [AtomType.ReactGridCol]: '',
  // [AtomType.ReactGridRow]: Grid.Row,
  [AtomType.ReactGridRow]: '',
  [AtomType.ReactCard]: Card,
  [AtomType.ReactCardGrid]: Card.Grid,
  [AtomType.ReactCardMeta]: Card.Meta,
  [AtomType.ReactTypography]: Typography,
  [AtomType.ReactTypographyTitle]: Typography.Title,
  [AtomType.ReactTypographyText]: Typography.Text,
  [AtomType.ReactTypographyParagraph]: Typography.Paragraph,
  [AtomType.ReactAlert]: Alert,
  [AtomType.ReactAffix]: Affix,
  [AtomType.ReactAutoComplete]: AutoComplete,
  [AtomType.ReactButton]: Button,
  [AtomType.ReactBreadcrumb]: Breadcrumb,
  [AtomType.ReactBreadcrumbItem]: Breadcrumb.Item,
  [AtomType.ReactDropdown]: Dropdown,
  [AtomType.ReactPageContainer]: PageContainer,
  [AtomType.ReactForm]: Form,
  [AtomType.ReactFormItem]: Form.Item,
  [AtomType.ReactFormList]: '',
  [AtomType.ReactFormItemHook]: '',
  [AtomType.ReactCheckbox]: Checkbox,
  [AtomType.ReactInput]: Input,
  [AtomType.ReactInputNumber]: InputNumber,
  [AtomType.ReactSelect]: Select,
  [AtomType.ReactSelectOption]: Select.Option,
  [AtomType.ReactRglContainer]: '',
  [AtomType.ReactRglItem]: '',
  [AtomType.ReactRglResponsiveContainer]: '',
  [AtomType.ReactProvider]: '',
  [AtomType.ReactModal]: Modal,
  [AtomType.ReactRadioGroup]: Radio.Group,
  [AtomType.ReactRadio]: Radio,
  [AtomType.ReactRate]: Rate,
  [AtomType.ReactSlider]: Slider,
  [AtomType.ReactSwitch]: Switch,
  [AtomType.ReactSpace]: Space,
  [AtomType.ReactDatePicker]: DatePicker,
  [AtomType.ReactDivider]: Divider,
  [AtomType.ReactPagination]: Pagination,
  [AtomType.ReactPageHeader]: PageHeader,
  [AtomType.ReactBadge]: Badge,
  [AtomType.ReactAvatar]: Avatar,
  [AtomType.ReactComment]: Comment,
  [AtomType.ReactCalendar]: Calendar,
  [AtomType.ReactDescriptions]: Descriptions,
  [AtomType.ReactDescriptionsItem]: Descriptions.Item,
  [AtomType.ReactEmpty]: Empty,
  [AtomType.ReactTimeline]: Timeline,
  [AtomType.ReactTimelineItem]: Timeline.Item,
  [AtomType.ReactTabs]: Tabs,
  [AtomType.ReactTabsTabPane]: Tabs.TabPane,
  [AtomType.ReactStatistic]: Statistic,
  [AtomType.ReactTooltip]: Tooltip,
  [AtomType.ReactTag]: Tag,
  [AtomType.ReactTree]: Tree,
  [AtomType.ReactDrawer]: Drawer,
  [AtomType.ReactProgress]: Progress,
  [AtomType.ReactResult]: Result,
  [AtomType.ReactSpin]: Spin,
  [AtomType.ReactSkeleton]: Skeleton,
  [AtomType.ReactAnchor]: Anchor,
  [AtomType.ReactAnchorLink]: Anchor.Link,
  [AtomType.ReactBackTop]: BackTop,
  [AtomType.ReactConfigProvider]: ConfigProvider,
  [AtomType.ReactPopconfirm]: Popconfirm,
  [AtomType.ReactTransfer]: Transfer as any,
  [AtomType.ReactTreeSelect]: TreeSelect,
  [AtomType.ReactTreeNode]: TreeSelect.TreeNode,
  [AtomType.ReactTimePicker]: TimePicker,
  [AtomType.ReactUpload]: Upload,
  [AtomType.ReactSteps]: Steps,
  [AtomType.ReactStepsStep]: Steps.Step,
  [AtomType.ReactCollapse]: Collapse,
  [AtomType.ReactCollapsePanel]: Collapse.Panel,
  [AtomType.ReactCarousel]: Carousel,
  [AtomType.ReactList]: List,
  [AtomType.ReactListItem]: List.Item,
  [AtomType.ReactListItemMeta]: List.Item.Meta,
  [AtomType.ReactMentions]: Mentions,
  [AtomType.ReactMentionsOption]: Mentions.Option,
  [AtomType.ReactLayout]: Layout,
  [AtomType.ReactLayoutHeader]: Layout.Header,
  [AtomType.ReactLayoutSider]: Layout.Sider,
  [AtomType.ReactLayoutContent]: Layout.Content,
  [AtomType.ReactLayoutFooter]: Layout.Footer,
  [AtomType.ReactCascader]: Cascader as any,
  [AtomType.ReactPopover]: Popover,
  [AtomType.ReactTable]: '',
  [AtomType.ReactRenderComponent]: '',
  [AtomType.ReactRenderContainer]: '',
  [AtomType.ReactMapper]: '',
}
