import { Icon } from '@ant-design/compatible'
import { VertexType } from '@prisma/client'
import {
  Affix,
  Alert,
  Anchor,
  AutoComplete,
  Avatar,
  BackTop,
  Badge,
  Breadcrumb,
  Button,
  Calendar,
  Card,
  Carousel,
  Cascader,
  Checkbox,
  Collapse,
  Comment,
  ConfigProvider,
  DatePicker,
  Descriptions,
  Divider,
  Drawer,
  Dropdown,
  Empty,
  Form,
  Input,
  InputNumber,
  Layout,
  List,
  Mentions,
  Menu,
  Modal,
  PageHeader,
  Pagination,
  Popconfirm,
  Popover,
  Progress,
  Radio,
  Rate,
  Result,
  Select,
  Skeleton,
  Slider,
  Space,
  Spin,
  Statistic,
  Steps,
  Switch,
  Tabs,
  Tag,
  TimePicker,
  Timeline,
  Tooltip,
  Transfer,
  Tree,
  TreeSelect,
  Typography,
  Upload,
} from 'antd'
import React from 'react'
import {
  CodelabForm,
  CodelabHtml,
  CodelabMapper,
  CodelabTable,
  Grid,
  Provider,
  RGL,
  RenderComponent,
} from '@codelab/alpha/ui/antd'

const PageContainer = ({ children, ...props }: any) => {
  return children ? <>{children}</> : <></>
}

/**
 * A map of VertexTypes to their corresponding React components.
 * When adding a new vertex type, add the corresponding mapping here
 */
export const elementTypeMap: Record<
  VertexType,
  React.ComponentType<any> | string
> = {
  [VertexType.React_Fragment]: React.Fragment,
  [VertexType.React_Html_Div]: 'div',
  [VertexType.React_Html_P]: 'p',
  [VertexType.React_Html_A]: 'a',
  [VertexType.React_Html_Span]: 'span',
  [VertexType.React_Text]: CodelabHtml.Text,
  [VertexType.React_Icon]: Icon,
  [VertexType.React_Menu]: Menu,
  [VertexType.React_Menu_Item]: Menu.Item,
  [VertexType.React_Menu_ItemGroup]: Menu.ItemGroup,
  [VertexType.React_Menu_SubMenu]: Menu.SubMenu,
  [VertexType.React_Grid_Col]: Grid.Col,
  [VertexType.React_Grid_Row]: Grid.Row,
  [VertexType.React_Card]: Card,
  [VertexType.React_Card_Grid]: Card.Grid,
  [VertexType.React_Card_Meta]: Card.Meta,
  [VertexType.React_Typography]: Typography,
  [VertexType.React_Typography_Title]: Typography.Title,
  [VertexType.React_Typography_Text]: Typography.Text,
  [VertexType.React_Typography_Paragraph]: Typography.Paragraph,
  [VertexType.React_Alert]: Alert,
  [VertexType.React_Affix]: Affix,
  [VertexType.React_AutoComplete]: AutoComplete,
  [VertexType.React_Button]: Button,
  [VertexType.React_Breadcrumb]: Breadcrumb,
  [VertexType.React_Breadcrumb_Item]: Breadcrumb.Item,
  [VertexType.React_Dropdown]: Dropdown,
  [VertexType.React_Page_Container]: PageContainer,
  [VertexType.React_Form]: Form,
  [VertexType.React_Form_Item]: Form.Item,
  [VertexType.React_Form_List]: CodelabForm.List,
  [VertexType.React_Form_ItemHook]: CodelabForm.ItemHook,
  [VertexType.React_Checkbox]: Checkbox,
  [VertexType.React_Input]: Input,
  [VertexType.React_InputNumber]: InputNumber,
  [VertexType.React_Select]: Select,
  [VertexType.React_Select_Option]: Select.Option,
  [VertexType.React_RGL_Container]: RGL.Container,
  [VertexType.React_RGL_Item]: RGL.Item,
  [VertexType.React_RGL_ResponsiveContainer]: RGL.ResponsiveContainer,
  [VertexType.React_Provider]: Provider.Default,
  [VertexType.React_Modal]: Modal,
  [VertexType.React_Radio_Group]: Radio.Group,
  [VertexType.React_Radio]: Radio,
  [VertexType.React_Rate]: Rate,
  [VertexType.React_Slider]: Slider,
  [VertexType.React_Switch]: Switch,
  [VertexType.React_Space]: Space,
  [VertexType.React_DatePicker]: DatePicker,
  [VertexType.React_Divider]: Divider,
  [VertexType.React_Pagination]: Pagination,
  [VertexType.React_PageHeader]: PageHeader,
  [VertexType.React_Badge]: Badge,
  [VertexType.React_Avatar]: Avatar,
  [VertexType.React_Comment]: Comment,
  [VertexType.React_Calendar]: Calendar,
  [VertexType.React_Descriptions]: Descriptions,
  [VertexType.React_Descriptions_Item]: Descriptions.Item,
  [VertexType.React_Empty]: Empty,
  [VertexType.React_Timeline]: Timeline,
  [VertexType.React_Timeline_Item]: Timeline.Item,
  [VertexType.React_Tabs]: Tabs,
  [VertexType.React_Tabs_TabPane]: Tabs.TabPane,
  [VertexType.React_Statistic]: Statistic,
  [VertexType.React_Tooltip]: Tooltip,
  [VertexType.React_Tag]: Tag,
  [VertexType.React_Tree]: Tree,
  [VertexType.React_Drawer]: Drawer,
  [VertexType.React_Progress]: Progress,
  [VertexType.React_Result]: Result,
  [VertexType.React_Spin]: Spin,
  [VertexType.React_Skeleton]: Skeleton,
  [VertexType.React_Anchor]: Anchor,
  [VertexType.React_Anchor_Link]: Anchor.Link,
  [VertexType.React_BackTop]: BackTop,
  [VertexType.React_ConfigProvider]: ConfigProvider,
  [VertexType.React_Popconfirm]: Popconfirm,
  [VertexType.React_Transfer]: Transfer as any,
  [VertexType.React_TreeSelect]: TreeSelect,
  [VertexType.React_TreeNode]: TreeSelect.TreeNode,
  [VertexType.React_TimePicker]: TimePicker,
  [VertexType.React_Upload]: Upload,
  [VertexType.React_Steps]: Steps,
  [VertexType.React_Steps_Step]: Steps.Step,
  [VertexType.React_Collapse]: Collapse,
  [VertexType.React_Collapse_Panel]: Collapse.Panel,
  [VertexType.React_Carousel]: Carousel,
  [VertexType.React_List]: List,
  [VertexType.React_List_Item]: List.Item,
  [VertexType.React_List_Item_Meta]: List.Item.Meta,
  [VertexType.React_Mentions]: Mentions,
  [VertexType.React_Mentions_Option]: Mentions.Option,
  [VertexType.React_Layout]: Layout,
  [VertexType.React_Layout_Header]: Layout.Header,
  [VertexType.React_Layout_Sider]: Layout.Sider,
  [VertexType.React_Layout_Content]: Layout.Content,
  [VertexType.React_Layout_Footer]: Layout.Footer,
  [VertexType.React_Cascader]: Cascader as any,
  [VertexType.React_Popover]: Popover,
  [VertexType.React_Table]: CodelabTable.Default,
  [VertexType.React_RenderComponent]: RenderComponent.Default,
  [VertexType.React_RenderContainer]: RenderComponent.Container,
  [VertexType.React_Mapper]: CodelabMapper.Default,
}
