/**
 * This is a flat list to have a central place to refer to the label
 */
export enum AntdTag {
  Affix = 'Affix',
  Alert = 'Alert',
  Anchor = 'Anchor',
  AnchorLink = 'Anchor.Link',
  AutoComplete = 'AutoComplete',
  Avatar = 'Avatar',
  BackTop = 'BackTop',

  Badge = 'Badge',
  Breadcrumb = 'Breadcrumb',
  BreadcrumbItem = 'Breadcrumb.Item',
  Grid = 'Grid',
  Row = 'Row',
  Col = 'Col',
  Space = 'Space',

  // Navigation Category
  Navigation = 'Navigation',
  // General Category
  General = 'General',
  Carousel = 'Carousel',
  Divider = 'Divider',
  BreadcrumbSeparator = 'Breadcrumb.Separator',
  Dropdown = 'Dropdown',
  DropdownButton = 'Dropdown.Button',
  Collapse = 'Collapse',
  Pagination = 'Pagination',
  PageHeader = 'PageHeader',
  Steps = 'Steps',
  StepsStep = 'Steps.Step',

  // Data Entry Category
  DataEntry = 'Data Entry',
  TypographyText = 'Typography.Text',
  Cascader = 'Cascader',
  Checkbox = 'Checkbox',
  CheckboxGroup = 'Checkbox.Group',
  DatePicker = 'DatePicker',
  Form = 'Form',
  FormItem = 'Form.Item',
  FormList = 'Form.List',
  Input = 'Input',
  FormProvider = 'Form.Provider',
  FormErrorList = 'Form.ErrorList',
  InputNumber = 'InputNumber',
  Mentions = 'Mentions',
  MentionsOption = 'Mentions.Option',
  Radio = 'Radio',
  RadioGroup = 'Radio.Group',
  Rate = 'Rate',
  Select = 'Select',
  SelectOption = 'Select.Option',
  Slider = 'Slider',
  Switch = 'Switch',
  TimePicker = 'TimePicker',
  Transfer = 'Transfer',
  TreeSelect = 'TreeSelect',
  Upload = 'Upload',

  // Data Display Category
  DataDisplay = 'Data Display',
  TypographyTitle = 'Typography.Title',
  // Layout Category
  Layout = 'Layout',
  Message = 'Message',
  Menu = 'Menu',
  CollapsePanel = 'Collapse.Panel',
  Notification = 'Notification',
  // Other Category
  Other = 'Other',
  CardGrid = 'Card.Grid',
  CardMeta = 'Card.Meta',
  Popconfirm = 'Popconfirm',
  Descriptions = 'Descriptions',
  DescriptionsItem = 'Descriptions.Item',
  Empty = 'Empty',
  Image = 'Image',
  List = 'List',
  ListItem = 'List.Item',
  ListItemMeta = 'List.Item.Meta',
  Popover = 'Popover',
  Segmented = 'Segmented',
  Statistic = 'Statistic',
  Skeleton = 'Skeleton',
  Tooltip = 'Tooltip',
  LayoutSider = 'Layout.Sider',
  TimelineItem = 'Timeline.Item',
  Button = 'Button',
  TabsTabPane = 'Tabs.TabPane',
  Tag = 'Tag',
  Table = 'Table',

  // Feedback Category
  Feedback = 'Feedback',
  Tabs = 'Tabs',
  Drawer = 'Drawer',
  Modal = 'Modal',
  Comment = 'Comment',
  Timeline = 'Timeline',
  Progress = 'Progress',
  Calendar = 'Calendar',
  Result = 'Result',
  Spin = 'Spin',
  Tree = 'Tree',

  Card = 'Card',
  Icon = 'Icon',
  Typography = 'Typography',
  TypographyParagraph = 'Typography.Paragraph',
  ConfigProvider = 'ConfigProvider',
}
