export enum TypeKind {
  PrimitiveType = 'PrimitiveType',
  ArrayType = 'ArrayType',
  InterfaceType = 'InterfaceType',
  EnumType = 'EnumType',
  LambdaType = 'LambdaType',
  ElementType = 'ElementType',
  ComponentType = 'ComponentType',
  RenderPropsType = 'RenderPropsType',
  ReactNodeType = 'ReactNodeType',
  UnionType = 'UnionType',
  MonacoType = 'MonacoType',
  PageType = 'PageType',
  AppType = 'AppType',
}
