export const DATA_COMPONENT_ID = 'data-component-id'
export const DATA_ID = 'data-id'
export const BUILDER_NONE_CLASS_NAME = 'Builder-none'
export const BINDING_WILDCARD = '*'
export const DATA_GRID = 'DATA-GRID'
export const ROOT_RENDER_CONTAINER_ID = 'render-root'
export const ROOT_ELEMENT_NAME = 'Root element'
export const PROVIDER_ROOT_ELEMENT_NAME = 'Provider Root Element'
