import { Theme as AntDTheme } from '@rjsf/antd'
import { withTheme } from '@rjsf/core'
import { Button } from 'antd'
import { JSONSchema7 } from 'json-schema'
import React, { ReactElement, useRef, useState } from 'react'
import { callbackWithParams } from '../../../utils/callbackWithParams'
import { JsonSchemaUniFormProps } from '../uniforms/Form-jsonSchema--types'
import { setSubmitControllerRef } from './Form-jsonSchema--ref'
import { JsonSchemaFormProps } from './Form-jsonSchema--types'

const ThemedForm = withTheme(AntDTheme)

/**
 * Read to use form, can be used with modal or standalone
 */
export type UniFormUseCaseProps<
  TData extends Record<any, unknown>
> = React.PropsWithChildren<
  Partial<
    Pick<
      JsonSchemaUniFormProps<TData>,
      'onSubmitError' | 'onSubmitSuccess' | 'submitRef' | 'autosave'
    >
  >
>
/**
 * A form that's generated by a JSON schema.
 * Note: the form doesn't keep any state. If you don't pass formData and onChange and manage the state in another place, it will reset the values on every render
 */
export const JsonSchemaForm = <TData extends Record<any, unknown>>({
  submitRef,
  hideSubmitButton,
  onSubmitSuccess,
  onSubmitError,
  widgets,
  schema,
  onSubmit = () => null,
  initialFormData = {} as TData,
  submitButtonProps = {},
  saveOnChange = false,
  idPrefix,
  ...props
}: JsonSchemaFormProps<TData>): ReactElement => {
  const [localFormData, setLocalFormData] = useState<TData>(initialFormData)

  // Assign a random ID prefix that we can use if a custom one is not defined, so we don't get ID collisions
  const randomIdPrefix = useRef(
    `form${Math.random().toString(36).substring(7)}`,
  )

  return (
    <ThemedForm
      widgets={widgets}
      schema={schema as JSONSchema7}
      onSubmit={({ formData }) => {
        return onSubmit({ formData })
          .then((r: any) => {
            callbackWithParams(onSubmitSuccess, r)

            // setLocalFormData({ ...initialFormData })
          })
          .catch((err: any) => {
            callbackWithParams(onSubmitError, err)
          })
      }}
      onChange={({ formData }) => {
        setLocalFormData(formData)

        if (saveOnChange) {
          onSubmit({ formData })
        }
      }}
      formData={localFormData}
      idPrefix={idPrefix || randomIdPrefix.current}
      {...props}
    >
      {/* This button exists because by default the Form from rjsf includes a submit button and you can't configure it, only replace it by a custom one.
       Since we might not want to use it and we want to submit  using the submitController, we need a way to hide it.
       So we need to add our own button and hide it with display: none, it works
       */}
      <Button
        htmlType="submit"
        style={{
          ...submitButtonProps?.style,
          ...(hideSubmitButton ? { display: 'none' } : {}),
        }}
        // Expose only a submit controller ref, so that we don't have to expose the whole button ref
        ref={setSubmitControllerRef(submitRef)}
        {...submitButtonProps}
      >
        Submit
      </Button>
    </ThemedForm>
  )
}
