#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# yarn lint:graphql
# terraform fmt -recursive .terraform

# yarn cli codegen --env=local

yarn cross-env TIMING=1 lint-staged --verbose

# ./libs/tools/scripts/src/lint/git.sh
