#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# yarn lint:graphql

yarn codegen --port 8081

# terraform fmt -recursive .terraform

yarn cross-env TIMING=1 lint-staged --verbose

./libs/tools/scripts/src/lint/git.sh