#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# yarn lint:graphql

# make hasura-metadata-export

# Prettify Hausra directory
# npx prettier --config .prettierrc.json --write hasura

yarn codegen

# terraform fmt -recursive .terraform

yarn cross-env TIMING=1 lint-staged --verbose

./scripts/lint/git.sh