#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn codegen

# We update dgraph schema once only here
./scripts/dgraph/update-schema.js

make build-dev-affected
make test-dev-affected
make e2e-dev-affected
# make build-storybook

./scripts/git.sh
