#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# yarn codegen

yarn cli tasks build --env test
yarn cli tasks unit --env test
#yarn cli tasks int --env test
yarn cli tasks e2e --env test

./scripts/git.sh
