import { registerAs } from '@nestjs/config'
import { get } from 'env-var'
import path from 'path'
import { DgraphTokens } from './dgraph.tokens'

export interface DgraphConfig {
  endpoint: string
  /**
   * This is the user maintained schema file
   */
  schemaFile: string
  /**
   * This is generated by appending api enums to the `schemaFile` above
   */
  schemaGeneratedFile: string
}

export const dgraphConfig = registerAs<() => DgraphConfig>(
  DgraphTokens.DgraphConfig.toString(),
  () => ({
    // This is the hand written Dgraph schema file, we use this file as the source to generate a new schema file
    schemaFile: path.resolve(process.cwd(), 'dgraph/schema.graphql'),
    // This is the generated schema file with Nest.js GrapphQL server enums appended, this is the acutal file used to update Dgraph
    schemaGeneratedFile: path.resolve(
      process.cwd(),
      'dgraph/schema.generated.graphql',
    ),
    endpoint: get('CODELAB_DGRAPH_ENDPOINT').required().asUrlString(),
  }),
)
