import type { PropsWithChildren } from 'react'
import React from 'react'
import { StyledComponentsRegistry } from './registry'

export const metadata = {
  description: 'Generated by create-nx-workspace',
  title: 'Welcome to demo2',
}

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}

export default RootLayout
